In [1]:
 # this code consists of actual tree implementation also using OOP
 # gini was used as a parameter , not entropy .  
 # iris dataset from sklearn was used
 # since iris dataset consists of continuous values, i categorised its values according to a range
 # concatenated iris.data and iris.target into a single dataset
 

In [2]:
from sklearn import datasets
iris=datasets.load_iris()
#converting continuous data into categorical data by dividing continuous data in various classes
for i in range(0,4):
    mean1=iris.data[:,i].mean()
    max1=iris.data[:,i].max()
    min1=iris.data[:,i].min()
    
    for j in range(0,150):
       

        if iris.data[j,i]<=min1+(mean1-min1)/2:
            iris.data[j,i]=min1
        elif iris.data[j,i]>min1+(mean1-min1)/2 and iris.data[j,i]<mean1:
            iris.data[j,i]=min1+ (mean1-min1)/2
        elif iris.data[j,i]>=mean1 and iris.data[j,i]<mean1+(max1-mean1)/2:
            iris.data[j,i]=mean1
        elif iris.data[j,i]>=mean1+(max1-mean1)/2 and iris.data[j,i]<=max1:
            iris.data[j,i]=mean1+(max1-mean1)/2  

iris.data 

irisX=iris.data
    

In [3]:
# combining the iris.data and iris.target by concatenation and making a single dataset
import numpy as np
iris.data=np.concatenate((iris.data,iris.target.reshape(-1,1)),axis=1)
iris.data

array([[ 5.07166667,  3.054     ,  1.        ,  0.1       ,  0.        ],
       [ 4.3       ,  2.527     ,  1.        ,  0.1       ,  0.        ],
       [ 4.3       ,  3.054     ,  1.        ,  0.1       ,  0.        ],
       [ 4.3       ,  3.054     ,  1.        ,  0.1       ,  0.        ],
       [ 4.3       ,  3.054     ,  1.        ,  0.1       ,  0.        ],
       [ 5.07166667,  3.727     ,  1.        ,  0.1       ,  0.        ],
       [ 4.3       ,  3.054     ,  1.        ,  0.1       ,  0.        ],
       [ 4.3       ,  3.054     ,  1.        ,  0.1       ,  0.        ],
       [ 4.3       ,  2.527     ,  1.        ,  0.1       ,  0.        ],
       [ 4.3       ,  3.054     ,  1.        ,  0.1       ,  0.        ],
       [ 5.07166667,  3.054     ,  1.        ,  0.1       ,  0.        ],
       [ 4.3       ,  3.054     ,  1.        ,  0.1       ,  0.        ],
       [ 4.3       ,  2.527     ,  1.        ,  0.1       ,  0.        ],
       [ 4.3       ,  2.527     ,  1. 

In [4]:
def unique_vals(rows, col):
    # Find the unique values for a column in a dataset
    return set([row[col] for row in rows])

In [5]:
unique_vals(iris.data,0)
#{4.2999999999999998,
 #5.0716666666666672,
 #5.8433333333333337,
 #6.871666666666667}

{4.2999999999999998, 5.0716666666666672, 5.8433333333333337, 6.871666666666667}

In [6]:

def class_counts(rows):
    """Counts the number of each type of example in a dataset."""
    counts = {}  # a dictionary of label -> count.
    for row in rows:
        # in our dataset format, the label is always the last column
        label = row[-1]
        if label not in counts:
            counts[label] = 0
        counts[label] += 1
    return counts
class_counts(iris.data)

{0.0: 50, 1.0: 50, 2.0: 50}

In [7]:
def is_numeric(value):
    """Test if a value is numeric."""
    return isinstance(value, int) or isinstance(value, float)

In [8]:
class Question:
    """A Question is used to partition a dataset.

    This class just records a 'column number' (e.g., 0 for sepal length) and a
    'column value' (e.g., 0.6). The 'match' method is used to compare
    the feature value in an example to the feature value stored in the
    question. See the demo below.
    """

    def __init__(self, column, value):
        self.column = column
        self.value = value

    def match(self, example):
        # Compare the feature value in an example to the
        # feature value in this question.
        val = example[self.column]
        if is_numeric(val):
            return val >= self.value
        else:
            return val == self.value

    def __repr__(self):
        # This is just a helper method to print
        # the question in a readable format.
        condition = "=="
        if is_numeric(self.value):
            condition = ">="
        return "Is %s %s %s?" % (
            iris.feature_names[self.column], condition, str(self.value))

In [9]:
Question(0, 3)
#Is sepal length (cm) == 3?
#Question(1,4)
#Is sepal length (cm) == 3?

Is sepal length (cm) >= 3?

In [10]:
q=Question(0,5)
q

Is sepal length (cm) >= 5?

In [11]:
example=iris.data[:,0]
q.match(example)



True

In [12]:
def partition(rows, question):
    """Partitions a dataset.
    For each row in the dataset, check if it matches the question/feature to split upon. If
    so, add it to 'true rows', otherwise, add it to 'false rows'.
    """
    true_rows, false_rows = [], []
    for row in rows:
        if question.match(row):
            true_rows.append(row)
        else:
            false_rows.append(row)
    return true_rows, false_rows

In [13]:
# Let's partition the training data based on whether rows are Red.
true_rows, false_rows = partition(iris.data,q)
# This will contain all the rows with sepal length >=5, which was condition for q.
true_rows

[array([ 5.07166667,  3.054     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.727     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.054     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.727     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.727     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.727     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.054     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.727     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.727     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.054     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.054     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.054     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.054     ,  1.        ,  0.1       ,  0.        ]),
 array([ 5.07166667,  3.0

In [14]:
def gini(rows):
    """Calculate the Gini Impurity for a list of rows."""
    counts = class_counts(rows)
    impurity = 1
    for lbl in counts:
        prob_of_lbl = counts[lbl] / float(len(rows))
        impurity -= prob_of_lbl**2
    return impurity
#no_mixing = [['Apple'],
#              ['Apple']]
# this will return 0
#gini(no_mixing)
# output=0

In [15]:
def info_gain(left, right, current_uncertainty):
    
   #Information Gain-The uncertainty of the starting node, minus the weighted impurity oftwo child nodes.
    # gives us the inforation gain for a split 
    
    p = float(len(left)) / (len(left) + len(right))
    return current_uncertainty - p * gini(left) - (1 - p) * gini(right)

In [16]:
current_uncertainty = gini(iris.data)
current_uncertainty # uncertainity of our current data

0.6666666666666665

In [17]:
def find_best_split(rows):
    
    #Find the best question to ask by iterating over every feature and calculating the information gain.
    
    best_gain = 0  # keeps track of the best information gain
    best_question = None  # keeps track of the feature that produced it
    current_uncertainty = gini(rows)
    n_features = len(rows[0]) - 1  # number of columns

    for col in range(n_features):  # for each feature

        values = set([row[col] for row in rows])  # unique values in the column

        for val in values:  # for each value

            question = Question(col, val)

            # try splitting the dataset
            true_rows, false_rows = partition(rows, question)

            # Skip this split if it doesn't divide the
            # dataset.
            if len(true_rows) == 0 or len(false_rows) == 0:
                continue

            # Calculate the information gain from this split
            gain = info_gain(true_rows, false_rows, current_uncertainty)

            if gain >= best_gain:
                best_gain, best_question = gain, question

    return best_gain, best_question, current_uncertainty

In [18]:
# Find the best question to ask first for iris dataset in the beginning.
best_gain, best_question,Gini = find_best_split(iris.data)
print(best_question)
print("current gini=",Gini)
print("information gain =",best_gain)


Is petal width (cm) >= 0.649333333333?
current gini= 0.6666666666666665
information gain = 0.3333333333333332


In [19]:
class Leaf:
    
    def __init__(self, rows):
        self.predictions = class_counts(rows)

In [20]:
class Decision_Node:
    
    def __init__(self,
                 question,
                 true_branch,
                 false_branch,gain,Gini):
        self.question = question
        self.true_branch = true_branch
        self.false_branch = false_branch
        self.gain=gain
        self.Gini=Gini

In [21]:
def build_tree(rows):
    gain, question,Gini = find_best_split(rows)

    if gain == 0:
        return Leaf(rows)
    
    true_rows, false_rows = partition(rows, question)

    # Recursively build the true branch.
    true_branch = build_tree(true_rows)

    # Recursively build the false branch.
    false_branch = build_tree(false_rows)

    return Decision_Node(question, true_branch, false_branch,gain,Gini)

In [22]:
def print_tree(node,level, spacing=""):
    
    print(spacing+"Level=",level)
    # Base case: we've reached a leaf
    if isinstance(node, Leaf):
        print (spacing + "(Leaf Node)  Predict", node.predictions)
        return
    # follows the in-order traversal of tree 
    print(spacing + "current gini is " + str(node.Gini))
    # Print the question at this node
    print(spacing + str(node.question) + " information gain on this split="+ str(node.gain))
    print()
    # Call this function recursively on the true branch
    print(spacing + '| True:')
    print_tree(node.true_branch,level+1, spacing + "  ")
    print()
    # Call this function recursively on the false branch
    print(spacing + '| False:')
    print_tree(node.false_branch,level+1, spacing + "  ")

In [23]:
my_tree = build_tree(iris.data)

In [24]:
# required output!

print_tree(my_tree,0)

Level= 0
current gini is 0.6666666666666665
Is petal width (cm) >= 0.649333333333? information gain on this split=0.3333333333333332

| True:
  Level= 1
  current gini is 0.5
  Is petal width (cm) >= 1.84933333333? information gain on this split=0.25757575757575757

  | True:
    Level= 2
    (Leaf Node)  Predict {2.0: 34}

  | False:
    Level= 2
    current gini is 0.36730945821854916
    Is petal length (cm) >= 5.32933333333? information gain on this split=0.15832304233558142

    | True:
      Level= 3
      (Leaf Node)  Predict {2.0: 8}

    | False:
      Level= 3
      current gini is 0.23781212841854948
      Is sepal length (cm) >= 5.84333333333? information gain on this split=0.014531041689186855

      | True:
        Level= 4
        current gini is 0.33425160697887973
        Is sepal width (cm) >= 3.054? information gain on this split=0.028797061524334255

        | True:
          Level= 5
          (Leaf Node)  Predict {1.0: 8}

        | False:
          Level= 5
     